services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - dokploy-network
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_KEY: ${APP_KEY}
      APP_URL: http://${APP_DOMAIN}
      DB_CONNECTION: mysql
      DB_HOST: mariadb
      DB_PORT: "3306"
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - app-storage:/var/www/html/storage

  web:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: always
    depends_on:
      - php
    networks:
      - dokploy-network
    volumes:
      - app-storage:/var/www/html/storage
      - ./:/var/www/html:ro
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dokploy-network"

      # Service (nama unik)
      - "traefik.http.services.ppob-svc.loadbalancer.server.port=80"

      # Router HTTP → redirect ke HTTPS
      - "traefik.http.routers.ppob-http.rule=Host(`ppob-baru.paymentpedami.com`)"
      - "traefik.http.routers.ppob-http.entrypoints=web"
      - "traefik.http.middlewares.ppob-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.ppob-http.middlewares=ppob-redirect"
      - "traefik.http.routers.ppob-http.service=ppob-svc"

      # Router HTTPS (tautkan eksplisit ke service)
      - "traefik.http.routers.ppob-https.rule=Host(`ppob-baru.paymentpedami.com`)"
      - "traefik.http.routers.ppob-https.entrypoints=websecure"
      - "traefik.http.routers.ppob-https.tls=true"
      - "traefik.http.routers.ppob-https.tls.certresolver=letsencrypt"
      - "traefik.http.routers.ppob-https.service=ppob-svc"

      # Security headers (pakai nama middleware UNIK)
      - "traefik.http.middlewares.ppob-sec.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.ppob-sec.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.ppob-sec.headers.stsPreload=true"
      - "traefik.http.middlewares.ppob-sec.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.ppob-sec.headers.browserXssFilter=true"
      - "traefik.http.middlewares.ppob-sec.headers.frameDeny=true"

      # Rate limit (nama middleware UNIK)
      - "traefik.http.middlewares.ppob-rate.ratelimit.average=100"
      - "traefik.http.middlewares.ppob-rate.ratelimit.burst=200"

      # PASANG middleware pada router HTTPS DALAM SATU BARIS
      - "traefik.http.routers.ppob-https.middlewares=ppob-sec,ppob-rate"

  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_DB_PASSWORD}
      MARIADB_ROOT_HOST: "%" 
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: ["mariadbd", "--skip-host-cache", "--skip-name-resolve"]
    ulimits:
      nofile: 1048576
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./my-tuning.cnf:/etc/mysql/conf.d/my-tuning.cnf:ro
      - ./init-users.sql:/docker-entrypoint-initdb.d/00-init-users.sql:ro
    networks:
      - dokploy-network
    #ports:
    #  - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dokploy-network"
      - "traefik.http.services.pma-svc.loadbalancer.server.port=80"

      - "traefik.http.routers.pma-http.rule=Host(`pma.paymentpedami.com`)"
      - "traefik.http.routers.pma-http.entrypoints=web"
      - "traefik.http.middlewares.pma-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.pma-http.middlewares=pma-redirect"
      - "traefik.http.routers.pma-http.service=pma-svc"

      - "traefik.http.routers.pma-https.rule=Host(`pma.paymentpedami.com`)"
      - "traefik.http.routers.pma-https.entrypoints=websecure"
      - "traefik.http.routers.pma-https.tls=true"
      - "traefik.http.routers.pma-https.tls.certresolver=letsencrypt"
      - "traefik.http.routers.pma-https.service=pma-svc"
    depends_on:
      - mariadb
    networks:
      - dokploy-network

volumes:
  app-storage:
  mariadb-data:

networks:
  dokploy-network:
    external: true
