services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - dokploy-network
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_KEY: ${APP_KEY}
      APP_URL: http://${APP_DOMAIN}
      DB_CONNECTION: mysql
      DB_HOST: mariadb
      DB_PORT: "3306"
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - app-storage:/var/www/html/storage

  web:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: always
    depends_on:
      - php
    networks:
      - dokploy-network
    volumes:
      - app-storage:/var/www/html/storage
      - ./:/var/www/html:ro
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      # Redirect HTTP -> HTTPS
      - "traefik.http.routers.app.entrypoints=web"
      - "traefik.http.routers.app.rule=Host(`ppob-baru.paymentpedami.com`)"
      - "traefik.http.middlewares.app-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.app.middlewares=app-https-redirect"

      # Router HTTPS
      - "traefik.http.routers.app-https.entrypoints=websecure"
      - "traefik.http.routers.app-https.rule=Host(`ppob-baru.paymentpedami.com`)"
      - "traefik.http.routers.app-https.tls=true"
      - "traefik.http.routers.app-https.tls.certresolver=letsencrypt"

      # Security headers (HSTS, XSS, MIME)
      - "traefik.http.middlewares.sec-headers.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.sec-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.sec-headers.headers.stsPreload=true"
      - "traefik.http.middlewares.sec-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.sec-headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.sec-headers.headers.frameDeny=true"
      - "traefik.http.routers.app-https.middlewares=sec-headers"

      - "traefik.http.middlewares.app-ratelimit.ratelimit.average=100"
      - "traefik.http.middlewares.app-ratelimit.ratelimit.burst=200"
      - "traefik.http.routers.app-https.middlewares=sec-headers,app-ratelimit"

  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_DB_PASSWORD}
      MARIADB_ROOT_HOST: "%" 
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: ["mariadbd", "--skip-host-cache", "--skip-name-resolve"]
    ulimits:
      nofile: 1048576
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./my-tuning.cnf:/etc/mysql/conf.d/my-tuning.cnf:ro
      - ./init-users.sql:/docker-entrypoint-initdb.d/00-init-users.sql:ro
    networks:
      - dokploy-network
    #ports:
    #  - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
    expose:
      - "80"
    labels:
      - "traefik.enable=true"

      # Router utama HTTPS
      - "traefik.http.routers.phpmyadmin.rule=Host(`pma.paymentpedami.com`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin.tls=true"
      - "traefik.http.routers.phpmyadmin.tls.certresolver=letsencrypt"

      # Router HTTP -> redirect ke HTTPS
      - "traefik.http.routers.phpmyadmin-redirect.rule=Host(`pma.paymentpedami.com`)"
      - "traefik.http.routers.phpmyadmin-redirect.entrypoints=web"
      - "traefik.http.routers.phpmyadmin-redirect.middlewares=redirect-https"
      - "traefik.http.middlewares.redirect-https.redirectscheme.scheme=https"

      # Pastikan port internal service
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
    depends_on:
      - mariadb
    networks:
      - dokploy-network

volumes:
  app-storage:
  mariadb-data:

networks:
  dokploy-network:
    external: true
